### ISSUE TITLE
It stopped working for me

### ISSUE THREAD

**Issue by emsit** [guyrotem/google-translate-server#4]
> google-translate-api@2.75.0 start /home/google-translate-server
> node server.js

loading values from .env file:
{ PORT: '9333',
  CLIENT_BASE_DOMAIN: 'http://localhost:5000',
  DATABASE_URL: 'postgres:///google_translate_server',
  ENABLE_PSQL: 'false' }
Topology initialized with:
{ externalApis: 
   { googleTranslateApi: 'https://translate.google.com/translate_a/single',
     googleTtsApi: 'https://translate.google.com/translate_tts',
     googleTranslateWebpage: 'https://translate.google.com/' } }
Pre-loaeded last TKK: null
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::9333
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at Server.setupListenHandle [as _listen2] (net.js:1351:14)
    at listenInCluster (net.js:1392:12)
    at Server.listen (net.js:1476:7)
    at Function.listen (/home/google-translate-server/node_modules/express/lib/application.js:617:24)
    at Object.startServer (/home/google-translate-server/scripts/run-server.js:22:6)
    at setProductionTopology.then (/home/google-translate-server/server.js:8:10)
    at _fulfilled (/home/google-translate-server/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/home/google-translate-server/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/home/google-translate-server/node_modules/q/q.js:796:13)
    at /home/google-translate-server/node_modules/q/q.js:604:44
    at runSingle (/home/google-translate-server/node_modules/q/q.js:137:13)
    at flush (/home/google-translate-server/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! google-translate-api@2.75.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the google-translate-api@2.75.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-10-16T05_55_46_877Z-debug.log

**Comment by emsit** [comment]
He's already working. I'm closing the issue.
